### ISSUE TITLE
Assignment Issues

### ISSUE THREAD

**Issue by sayedtaqui** [bhautikgosai96/blog_app#1]
Thanks for creating the assignment. Some of the requirements of the assignment are not fulfilled.
https://github.com/rtCamp/hiring-assignments/tree/master/React-Developer#task--1

1. Footer - Brand Logo, Footer Menu
2. Home - Should Display Latest # Posts ( Title and excerpt only ) with pagination
3. Category - Display Latest # Posts with pagination
4. Should be SEO friendly (server-side rendering)

Other than that.
- Please use minimal CSS to style your post content.
- Please use post title instead of displaying post id in post blocks.
- Some of the posts like 1173 are displaying HTML markup.
- When the pagination changes the URL should update.

**Comment by bhautikgosai96** [comment]
I have updated changes. Can you please provide your feedback?

**Comment by sayedtaqui** [comment]
@bhautikgosai96 Cannot see the demo app http://blog-assignment.herokuapp.com/
![image](https://user-images.githubusercontent.com/6297436/59889092-563c5100-93e8-11e9-923b-114874333258.png)

**Comment by bhautikgosai96** [comment]
> @bhautikgosai96 Cannot see the demo app http://blog-assignment.herokuapp.com/
> ![image](https://user-images.githubusercontent.com/6297436/59889092-563c5100-93e8-11e9-923b-114874333258.png)

Hi sayedtaqui,

I have updated changes. Can you please provide your feedback?

**Comment by mohdsayed** [comment]
Looks good thanks
